install: true
script: true
after_success:
  - git tag v0.1.0 -m 'Release version 0.1.0' && git push --tags -q $REPOSITORY
env:
  global:
    - secure: "fmErV9oidV9kmJAzbeEiqzJBNNDeTAfVmnnxn9NLqsO6XuxAKap993SIQMLwZRpTIsJNkQCz3jrNnJuVvHsRB6blntRnsV92UHLkm0ZaS9TkZ72BVfDE8cv6KRR69x2AlYy/Jwog093udlgZX5pv/AMKEPNHAvrXDHJ0TY1GC7Y="
    - secure: "qCF7B2pAomagNXhNK6pzADpyGpNUnB/sDI1gvpbsi7oY3QL67Nc+bmjXjVnCrWYmn+tRRXub8l1/BTmAHPvtoY5h7ethSndxCwa62lUASn2wv8vPQlqxnjvNE594xrc1Mf8Fvjps9uHTUqQyF5AT9uRYsXQcg8EQKsTMjBqdaMM="
    - secure: "ohpuef+jtU6ePw+LFGK//5KfO6RMNqZ59m472I6cFFJHENMUwm9Fr1vfZOb8ri8cwgbmEbFYujr8fLrFwnpklXfuzlcS4J5Ww4dADb7owQWWPacNoF0vEU2DqJYMk6JkNV09Y8GZ7f4CeZoUwV+T1ge0A8QS4mRlZ4rlxjWv4QA="
    - GIT_AUTHOR_NAME=$GIT_COMMITTER_NAME
    - GIT_AUTHOR_EMAIL=$GIT_COMMITTER_EMAIL

